[package]
name = "nuclear_data"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
polars = {version = "0.45.1", featues = ["lazy"]}
rayon = "1.10.0"
strum = "0.26.3"
strum_macros = "0.26.4"
tempfile = "3.15.0"
thiserror = "2.0.11"
